services:

  game-server:

    # Ключевое слово "build" позволяет задать
    # путь к файлу Dockerfile, который нужно использовать для создания образа,
    # который позволит запустить сервис.

    build:
      # Контекст для сборки образа
      context: .
      # Имя Docker-файла из которого будет собран образ
      dockerfile: Dockerfile

    # Команда, которую нужно запустить после создания образа.

    command: node server.js

    # При использовании 'ports' применяется следующая конструкция: [порт компьютера]:[порт контейнера]

    ports:
      - 8081:8080

    volumes:
      # Текущая директория пробрасывается в директорию /app внутри контейнера
      - ".:/2048-game"

  game-server2:

    build:
      context: .
      dockerfile: Dockerfile


    command: node server.js

    ports:
      - 8001:8080

    volumes:
      - ".:/2048-game"
